import type { GetServerSidePropsContext, InferGetServerSidePropsType, NextPage } from "next";
import { getServerSession } from "next-auth/next"
import { authOptions } from "~/server/auth";
import Head from "next/head";
import { signIn, signOut, useSession, getProviders } from "next-auth/react";

import { type Provider } from "next-auth/providers";

const Home: NextPage = ({ providers }: InferGetServerSidePropsType<typeof getServerSideProps>) => {
  const { data: sessionData } = useSession();
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });
  // const {data: accessToken} = api.spotify.getAccessToken.useQuery();
  // console.log("accessToken: ", accessToken)
  // const providers = getProviders()

  // if (accessToken) {
  //   // const {data: currentSong} = api.spotify.getCurrentSong.useQuery({access_token: accessToken.access_token});
  // }
  return (
    <>
      <Head>
        <title>Macken Spotify App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#0a4a21] to-[#102615]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Log in to <span className="text-[#1ed760]">macken-spotify</span> App
          </h1>
         
          {Object.values(providers).map((provider) => (
            <div key={provider.name}>
              {/* eslint-disable-next-line @typescript-eslint/no-misused-promises */}
              <button className="flex w-[10vw} h-10 bg-[#525252] p-4 text-center items-center" onClick={() => signIn(provider.id, {callbackUrl: "/playback", redirect: false })}>
                Sign in with {provider.name}
              </button>
            </div>
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;

export async function getServerSideProps(context: GetServerSidePropsContext) {
  const session = await getServerSession(context.req, context.res, authOptions);
  
  // If the user is already logged in, redirect.
  // Note: Make sure not to redirect to the same page
  // To avoid an infinite loop!
  if (session) {
    return { redirect: { destination: "/playback" } };
  }

  const providers = await getProviders();
  
  return {
    props: { providers: providers ?? [] },
  }
}